export default {
  route: {
    path: '/assets',

    routes: [
      {
        path: '/',
        redirect: '/assets',
      },
      {
        path: '/assets',
        // icon: 'DatabaseOutlined',
        name: 'ASSETS',
        component: './assets/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/asset-history/:id',
        hideInMenu: true,
        name: 'ASSET HISTORY',
        component: './asset_history/list',
      },
      {
        path: '/archieve-assets',
        // icon: 'DatabaseOutlined',
        name: 'ARCHIEVE ASSETS',
        component: './assets/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/assetstype',
        // icon: 'form',
        name: 'ASSET TYPES',
        component: './assetstypes/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/partnumbers',
        // icon: 'form',
        name: 'PARTNUMBER',
        component: './partnumbers/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/pallets',
        // icon: 'form',
        name: 'PALLETS',
        component: './pallets/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/certus',
        // icon: 'form',
        name: 'CERTUS',
        component: './certus/list',
        // authority: [ 'admin' ],
      },
      // {
      //   path: '/assetvalues',
      //   // icon: 'form',
      //   name: 'ASSETVALUES',
      //   component: './exportassetsvalue',
      //   // authority: [ 'admin' ],
      // },
      // {
      //   path: '/brokerbin',
      //   // icon: 'form',
      //   name: 'BROKERBIN',
      //   component: './brokerbin',
      //   // authority: [ 'admin' ],
      // },
      {
        path: '/clientusersList/:id',
        // icon: 'form',
        name: 'CLIENT USERS LIST',
        hideInMenu: true,
        component: './users/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/clientusersList',
        // icon: 'form',
        name: 'CLIENT USERS LIST',
        hideInMenu: true,
        component: './users/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/partnerusersList/:id',
        // icon: 'form',
        name: 'PARTNER USERS LIST',
        hideInMenu: true,
        component: './users/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/partnerusersList',
        // icon: 'form',
        name: 'PARTNER USERS LIST',
        hideInMenu: true,
        component: './users/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/projects',
        // icon: 'form',
        name: 'PROJECTS',
        component: './projects/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/clients',
        // icon: 'form',
        name: 'CLIENTS',
        component: './clients/list',
        // authority: [ 'admin' ],
      },
      // {
      // 	path: '/createproject',
      // 	// icon: 'form',
      // 	name: 'CREATE PROJECT',
      // 	hideInMenu: true,
      // 	component: './projects/components/AddNewProject',
      // 	// authority: [ 'admin' ],
      // },
      {
        path: '/createproject',
        // icon: 'form',
        name: 'CREATE PROJECT',
        hideInMenu: true,
        component: './projects/components/CreateForm',
        // authority: [ 'admin' ],
      },
      {
        path: '/projectassets/:id',
        // icon: 'form',
        name: 'PROJECT ASSETS',
        hideInMenu: true,
        component: './assets/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/updateproject/:id',
        // icon: 'form',
        name: 'UPDATE PROJECT',
        hideInMenu: true,
        component: './projects/components/CreateForm',
        // component: './projects/components/AddNewProject',
        // authority: [ 'admin' ],
      },
      {
        path: '/createclient',
        // icon: 'form',
        name: 'CREATE CLIENT',
        hideInMenu: true,
        component: './clients/components/AddNew',
        // authority: [ 'admin' ],
      },
      {
        path: '/updateclient/:id',
        // icon: 'form',
        name: 'UPDATE CLIENT',
        hideInMenu: true,
        component: './clients/components/AddNew',
        // authority: [ 'admin' ],
      },
      {
        path: '/createaddress/:id',
        // icon: 'form',
        hideInMenu: true,
        name: 'CREATE SUB ADDRESS',
        component: './clients/components/CreateSubAddress',
        // authority: [ 'admin' ],
      },
      {
        path: '/updateaddress/:id',
        // icon: 'form',
        hideInMenu: true,
        name: 'Update SUB ADDRESS',
        component: './clients/components/CreateSubAddress',
        // authority: [ 'admin' ],
      },
      {
        path: '/clientsubaddress/:id',
        // icon: 'form',
        hideInMenu: true,
        name: 'SUB ADDRESS',
        component: './clients/components/SubAddressList',
        // authority: [ 'admin' ],
      },
      {
        path: '/createpartner',
        hideInMenu: true,
        name: 'CREATE PARTNER',
        component: './partners/components/AddNew',
        // authority: [ 'admin' ],
      },

      {
        path: '/partners',
        // icon: 'form',
        name: 'PARTNERS',
        component: './partners/list',
      },
      {
        path: '/updatepartner/:id',
        // icon: 'form',
        name: 'UPDATE PARTNER',
        hideInMenu: true,
        component: './partners/components/AddNew',
        // authority: [ 'admin' ],
      },
      {
        path: '/palletsassets/:id',
        // icon: 'form',
        name: 'PROJECT ASSETS',
        hideInMenu: true,
        component: './assets/list',
        // authority: [ 'admin' ],
      },
      {
        path: '/files',
        // icon: 'form',
        name: 'FILES',
        component: './file/list',
        // authority: [ 'admin' ],
      },
      {
        component: '404',
      },
    ],
  },
  // location: {
  //   pathname: '/assets',
  // },
};